apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrarouter
  namespace: infrarouter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: infrarouter
  template:
    metadata:
      labels:
        app: infrarouter
    spec:
      containers:
        - name: infrarouter
          image: xavor/infrarouter-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: infrarouter-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: infrarouter-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: infrarouter-data
